---
    name: Lint Code Base
    
    on:
      push:
        branches: 
          [main, master]
      pull_request:
        branches: 
          [main, master]
    
      workflow_dispatch:
    
        
    jobs:
      build:
        name: Flutter Build
        runs-on: ubuntu-latest
        env: 
          FLUTTER_VERSION: "3.13.5"
        steps:
          - name: Checkout Code
            uses: actions/checkout@v3
            with:
              fetch-depth: 0
    
          - name: Flutter Actions
            uses: subosito/flutter-action@v2
            with:
              channel: stable
              flutter-version: 3.13.5
              cache: true
          
          - run: flutter --version
          - run: flutter pub get
          - run: flutter analyze